language: c

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.9-linux64.tar.xz
  - tar xf arduino-1.6.9-linux64.tar.xz
  - sudo mv arduino-1.6.9 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  
install:
  # install MPU6050 lib
  - ln -s $PWD/i2cdevlib/Arduino/MPU6050 /usr/local/share/arduino/libraries/MPU6050
  # install I2Cdev lib
  - ln -s $PWD/i2cdevlib/Arduino/I2Cdev /usr/local/share/arduino/libraries/I2Cdev
  # install CRC32 lib
  - ln -s $PWD/CRC32 /usr/local/share/arduino/libraries/CRC32
  
script:
  - arduino --verify --board arduino:avr:mini:cpu=atmega328 $PWD/accel_firmware/accel_firmware.ino

notifications:
  email:
    on_success: change
    on_failure: change

